### PR TITLE
added computer science support

### PR DESCRIPTION
**Pull request by blackTay**
New:
- Package to write pseudo code
- Easy notation of asymptotics

Compsc option is part of mega (and upwards) option

### CODE REVIEW

**Comment by niklasbogensperger** [comment]
@blackTay, please review my changes - especially the breaking ones introduced in commits 667d87b and 8219f1e

**Comment by blackTay** [comment]
Changes reviewed. Only issue: "compsci" ambiguity

**Comment by blackTay** [comment]
- Created probability module.
- Some compsci updates, in particular to algpseudocode
- Compsci contains now only computer science, now probability. 
- More examples for compsci and probability modules

**Review by niklasbogensperger — APPROVED** [review]
We can finally merge this now, looks good. I will make some smaller tweaks after this is merged.

**Pull request merged**
